trigger:
  branches:
    include:
      - main

pool:
  vmImage: "ubuntu-latest"

variables:
  sqlFolder: "sql/2025-04"

stages:
- stage: ValidateSQL
  displayName: "Validate SQL Changes"
  jobs:
  - job: Lint
    steps:
    - task: PowerShell@2
      inputs:
        targetType: "inline"
        script: |
          $fail = $false
          $files = Get-ChildItem -Recurse "$(sqlFolder)" -Include *.sql
          foreach ($file in $files) {
            $content = Get-Content $file.FullName -Raw
            if ($content -match "DROP\s+TABLE|DELETE\s+FROM|TRUNCATE") {
              Write-Host "Risky SQL command found in $($file.FullName)"
              $fail = $true
            }
          }
          if ($fail) {
            throw "Validation failed. Unsafe SQL detected."
          }
